spring:
  application:
    name: demo
  ai.model.chat: ollama
  ai.ollama.chat.options.model: llama3.2:1b

logging:
  level:
    org.springframework.ai.chat.client.advisor : debug
    com.avinash.demo: debug